### ISSUE TITLE
review conditions on when there is not a gameday

### ISSUE THREAD

**Issue by aletson** [aletson/votefinder-web#211]
```
App 2706 output: Traceback (most recent call last):
App 2706 output:   File "/var/www/venvs/vfprod37/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
App 2706 output:     response = get_response(request)App 2706 output:   File "/var/www/venvs/vfprod37/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
App 2706 output:     response = self.process_exception_by_middleware(e, request)App 2706 output:   File "/var/www/venvs/vfprod37/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
App 2706 output:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
App 2706 output:   File "/var/www/html/votefinder.org/votefinder/main/views.py", line 133, in game
App 2706 output:     manual_votes = Vote.objects.filter(game=game, manual=True, post__id__gte=gameday.start_post.id).order_by('id')App 2706 output: AttributeError: 'NoneType' object has no attribute 'start_post'
```

**Comment by aletson** [comment]
Fixed in 3.7.3.
